#ifndef SYSCALLS_H
#define SYSCALLS_H

typedef enum {
    SYS_PRINT         = 0,

    SYS_GETPID        = 1,
    SYS_GETPPID       = 2,
    SYS_FORK          = 3,
    SYS_EXEC          = 4,
    SYS_EXIT          = 5,
    SYS_WAITPID       = 6,
    SYS_SLEEP         = 7,

    SYS_SETSID        = 8,
    SYS_SETPGID       = 9,
    SYS_GETPGID       = 10,
    SYS_GETPGRP       = 11,

    SYS_KILL          = 12,
    SYS_SIGNAL        = 13,
    SYS_SIGACTION     = 14,
    SYS_SIGPROCMASK   = 15,
    SYS_SIGRETURN     = 16,
    SYS_SIGPENDING    = 17,
    SYS_SIGSUSPEND    = 18,
    SYS_ALARM         = 19,
    SYS_SETITIMER     = 20,

    SYS_OPEN          = 21,
    SYS_READ          = 22,
    SYS_WRITE         = 23,
    SYS_CLOSE         = 24,
    SYS_LSEEK         = 25,
    SYS_IOCTL         = 26,
    SYS_FCNTL         = 27,
    SYS_DUP           = 28,
    SYS_DUP2          = 29,
    SYS_PIPE          = 30,
    SYS_SELECT        = 31,
    SYS_POLL          = 32,

    SYS_STAT          = 33,
    SYS_FSTAT         = 34,
    SYS_ACCESS        = 35,
    SYS_CHMOD         = 36,
    SYS_CHOWN         = 37,
    SYS_UMASK         = 38,
    SYS_TRUNCATE      = 39,
    SYS_FTRUNCATE     = 40,
    SYS_SYNC          = 41,
    SYS_FSYNC         = 42,
    SYS_MKNOD         = 43,

    SYS_CREATE        = 44,
    SYS_MKDIR         = 45,
    SYS_RMDIR         = 46,
    SYS_DELETE        = 47,
    SYS_UNLINK        = 48,
    SYS_RENAME        = 49,
    SYS_LINK          = 50,
    SYS_SYMLINK       = 51,
    SYS_READLINK      = 52,
    SYS_GETDENTS      = 53,
    SYS_CHDIR         = 54,
    SYS_GETCWD        = 55,
    SYS_CHROOT        = 56,

    SYS_MOUNT         = 57,
    SYS_UMOUNT        = 58,
    SYS_REBOOT        = 59,
    SYS_UNAME         = 60,

    SYS_BRK           = 61,
    SYS_MMAP          = 62,
    SYS_MUNMAP        = 63,
    SYS_MPROTECT      = 64,

    SYS_SHMGET        = 65,
    SYS_SHMAT         = 66,
    SYS_SHMDT         = 67,
    SYS_SHMCTL        = 68,

    SYS_GETTIMEOFDAY  = 69,
    SYS_CLOCK_GETTIME = 70,
    SYS_NANOSLEEP     = 71,

    SYS_GETUID        = 72,
    SYS_GETGID        = 73,
    SYS_GETEUID       = 74,
    SYS_GETEGID       = 75,
    SYS_SETUID        = 76,
    SYS_SETGID        = 77,

    SYS_SOCKET        = 78,
    SYS_BIND          = 79,
    SYS_CONNECT       = 80,
    SYS_LISTEN        = 81,
    SYS_ACCEPT        = 82,
    SYS_SEND          = 83,
    SYS_RECV          = 84,
    SYS_SENDTO        = 85,
    SYS_RECVFROM      = 86,
    SYS_SHUTDOWN      = 87,
    SYS_SETSOCKOPT    = 88,
    SYS_GETSOCKOPT    = 89,
    SYS_PING_ECHO     = 90,
    SYS_NETCFG_SET    = 91,

    SYS_MODULE_LOAD   = 92,
    SYS_MODULE_UNLOAD = 93,
    SYSCALL_COUNT     = 94,
} syscall_num_t;

#endif 
