[package]
name    = "cact_sync"
version = "0.1.0"
edition = "2021"

[lib]
name       = "cact_sync"
crate-type = ["lib"]

[profile.release]
panic           = "abort"
opt-level       = 2
lto             = true
codegen-units   = 1
overflow-checks = true
debug           = false

[profile.dev]
panic           = "abort"
overflow-checks = true
