[package]
name = "cact_vfs"
version = "0.1.0"
edition = "2021"

[lib]
name = "cact_vfs"
crate-type = ["lib"]

[dependencies]
cact_sync = { path = "../../kernel/sync" }
cact_mm = { path = "../../kernel/memory/rust_mm" }

[profile.release]
panic = "abort"
opt-level = 2
lto = true
codegen-units = 1
overflow-checks = true
debug = false

[profile.dev]
panic = "abort"
overflow-checks = true
